// http://jsbin.com/jeqanuhezi/edit?html,js,console,output
// https://github.com/lodash/lodash/blob/2.4.1/doc/README.md

var expandedLodashModuleMap = {
    arrays: [
        'compact',
        'difference',
        'findIndex',
        'findLastIndex',
        'first',
        'flatten',
        'indexOf',
        'initial',
        'intersection',
        'last',
        'lastIndexOf',
        'pull',
        'range',
        'remove',
        'rest',
        'sortedIndex',
        'union',
        'uniq',
        'without',
        'xor',
        'zip',
        'zipObject'
    ],
    collections: [
        'at',
        'contains',
        'countBy',
        'every',
        'filter',
        'find',
        'findLast',
        'forEach',
        'forEachRight',
        'groupBy',
        'indexBy',
        'invoke',
        'map',
        'max',
        'min',
        'pluck',
        'reduce',
        'reduceRight',
        'reject',
        'sample',
        'shuffle',
        'size',
        'some',
        'sortBy',
        'toArray',
        'where'
    ],
    functions: [
        'after',
        'bind',
        'bindAll',
        'bindKey',
        'compose',
        'curry',
        'debounce',
        'defer',
        'delay',
        'memoize',
        'once',
        'partial',
        'partialRight',
        'throttle',
        'wrap'
    ],
    objects: [
        'assign',
        'clone',
        'cloneDeep',
        'create',
        'defaults',
        'findKey',
        'findLastKey',
        'forIn',
        'forInRight',
        'forOwn',
        'forOwnRight',
        'functions',
        'has',
        'invert',
        'isArguments',
        'isArray',
        'isBoolean',
        'isDate',
        'isElement',
        'isEmpty',
        'isEqual',
        'isFinite',
        'isFunction',
        'isNaN',
        'isNull',
        'isNumber',
        'isObject',
        'isPlainObject',
        'isRegExp',
        'isString',
        'isUndefined',
        'keys',
        'mapValues',
        'merge',
        'omit',
        'pairs',
        'pick',
        'transform',
        'values'
    ],
    utilities: [
        'now',
        'constant',
        'createCallback',
        'escape',
        'identity',
        'mixin',
        'noConflict',
        'noop',
        'parseInt',
        'property',
        'random',
        'result',
        'runInContext',
        'template',
        'times',
        'unescape',
        'uniqueId'
    ]
};

var lodashAliasesMap = {
    drop: 'rest',
    head: 'first',
    object: 'zipObject',
    tail: 'rest',
    take: 'first',
    unique: 'uniq',
    unzip: 'zip',

    all: 'every',
    any: 'some',
    collect: 'map',
    detect: 'find',
    each: 'forEach',
    eachRight: 'forEachRight',
    findWhere: 'find',
    foldl: 'reduce',
    foldr: 'reduceRight',
    include: 'contains',
    inject: 'reduce',
    select: 'filter',

    extend: 'assign',
    methods: 'functions'
};

var lodashModuleMap = require('lodash').reduce(expandedLodashModuleMap, (acc, group, key) => {
    group.forEach(s => { acc[s] = `${key}/${s}`; });
    return acc;
}, {});

module.exports = {
    lodashModuleMap,
    lodashAliasesMap
};
